environment:
  matrix:
  - TOXENV: py27
    PYTHON_PATH: C:\Python27
    JEDI_TEST_ENVIRONMENT: 27
  - TOXENV: py27
    PYTHON_PATH: C:\Python27
    JEDI_TEST_ENVIRONMENT: 34
  - TOXENV: py27
    PYTHON_PATH: C:\Python27
    JEDI_TEST_ENVIRONMENT: 35
  - TOXENV: py27
    PYTHON_PATH: C:\Python27
    JEDI_TEST_ENVIRONMENT: 36
  - TOXENV: py27
    PYTHON_PATH: C:\Python27
    JEDI_TEST_ENVIRONMENT: 37

  - TOXENV: py34
    PYTHON_PATH: C:\Python34
    JEDI_TEST_ENVIRONMENT: 27
  - TOXENV: py34
    PYTHON_PATH: C:\Python34
    JEDI_TEST_ENVIRONMENT: 34
  - TOXENV: py34
    PYTHON_PATH: C:\Python34
    JEDI_TEST_ENVIRONMENT: 35
  - TOXENV: py34
    PYTHON_PATH: C:\Python34
    JEDI_TEST_ENVIRONMENT: 36
  - TOXENV: py34
    PYTHON_PATH: C:\Python34
    JEDI_TEST_ENVIRONMENT: 37

  - TOXENV: py35
    PYTHON_PATH: C:\Python35
    JEDI_TEST_ENVIRONMENT: 27
  - TOXENV: py35
    PYTHON_PATH: C:\Python35
    JEDI_TEST_ENVIRONMENT: 34
  - TOXENV: py35
    PYTHON_PATH: C:\Python35
    JEDI_TEST_ENVIRONMENT: 35
  - TOXENV: py35
    PYTHON_PATH: C:\Python35
    JEDI_TEST_ENVIRONMENT: 36
  - TOXENV: py35
    PYTHON_PATH: C:\Python35
    JEDI_TEST_ENVIRONMENT: 37

  - TOXENV: py36
    PYTHON_PATH: C:\Python36
    JEDI_TEST_ENVIRONMENT: 27
  - TOXENV: py36
    PYTHON_PATH: C:\Python36
    JEDI_TEST_ENVIRONMENT: 34
  - TOXENV: py36
    PYTHON_PATH: C:\Python36
    JEDI_TEST_ENVIRONMENT: 35
  - TOXENV: py36
    PYTHON_PATH: C:\Python36
    JEDI_TEST_ENVIRONMENT: 36
  - TOXENV: py36
    PYTHON_PATH: C:\Python36
    JEDI_TEST_ENVIRONMENT: 37

  - TOXENV: py37
    PYTHON_PATH: C:\Python37
    JEDI_TEST_ENVIRONMENT: 27
  - TOXENV: py37
    PYTHON_PATH: C:\Python37
    JEDI_TEST_ENVIRONMENT: 34
  - TOXENV: py37
    PYTHON_PATH: C:\Python37
    JEDI_TEST_ENVIRONMENT: 35
  - TOXENV: py37
    PYTHON_PATH: C:\Python37
    JEDI_TEST_ENVIRONMENT: 36
  - TOXENV: py37
    PYTHON_PATH: C:\Python37
    JEDI_TEST_ENVIRONMENT: 37
install:
  - git submodule update --init --recursive
  - set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%
  - pip install tox
build_script:
  - tox
